global:
  scrape_interval:     2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s # переопределение global.scrape_interval
    static_configs:
      - targets: [ "orders_management_system:8084" ]

  - job_name: "app"
    static_configs:
      - targets: [ "host.docker.internal:2112" ]