// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Person struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Pet  *Pet   `json:"pet,omitempty"`
}

type Pet struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}
